apiVersion: v2
name: helm-cluster
appVersion: "1.0"
description: A Helm chart for Logging and Tracing Transaction in a NetJS Environment
version: 1.0.0
type: application
dependencies:
  - name: elasticsearch
    version: "7.17.3"
    repository: https://helm.elastic.co
  - name: kibana
    version: "7.17.3"
    repository: https://helm.elastic.co
  - name: prometheus-elasticsearch-exporter
    version: 5.0.0
    repository: https://prometheus-community.github.io/helm-charts
